#@schema attach="data/values"
---
#@schema/doc "Domain of the system."
#@schema/type "string"
system_domain: ~
#@schema/doc "The namespace where cf components are installed."
#@schema/type "string"
system_namespace: ~

#@schema/doc "cf-k8s logging images"
images:
  #@schema/doc "log-cache image."
  log_cache: "logcache/log-cache@sha256:1074a8a64f56d1967758cf9cbd3d388b2e5bd295768231ebbaa9ae8febb7e90a"
  #@schema/doc "syslog-server image."
  syslog_server: "logcache/syslog-server@sha256:7a6c85226bb0f92e870c1bbe6555261c9946cdcd8fed2aeac854b7ea0b369a99"
  #@schema/doc "log-cache gateway image."
  log_cache_gateway: "logcache/log-cache-gateway@sha256:845998ef9769d78b43555eb18757b5f24571fefbe4a267c0ffa7e69071b38177"
  #@schema/doc "cf-k8s-logging image."
  fluent: "logcache/cf-k8s-logging@sha256:44e20fa761fb67436eabd70a226d88ca7398619aaa2b3b468405017c75fd9607"
  #@schema/doc "log-cache-cf-auth-proxy image."
  cf_auth_proxy: "logcache/log-cache-cf-auth-proxy@sha256:2fa3c3fc7a4d8ed006502aa239ca95a936ec69eb850de5790b057adcc26cb433"

#@schema/doc "log-cache ca configuration."
log_cache_ca:
  #@schema/doc "Base64-encoded ca for the log cache."
  #@schema/type "string"
  crt: ~
  #@schema/doc "Base64-encoded private key for the ca cert."
  #@schema/type "string"
  key: ~

#@schema/doc "log-cache certificate configuration."
log_cache:
  #@schema/doc "Base64-encoded cert for the log cache requires CN of log-cache."
  #@schema/type "string"
  crt: ~
  #@schema/doc "Base64-encoded private key for the cert."
  #@schema/type "string"
  key: ~

#@schema/doc "log-cache metrics configuration."
log_cache_metrics:
  #@schema/doc "Base64-encoded cert for the log cache metrics requires CN of log-cache-metrics."
  #@schema/type "string"
  crt: ~
  #@schema/doc "Base64-encoded private key for the log cache metrics cert."
  #@schema/type "string"
  key: ~

#@schema/doc "log-cache gateway configuration."
log_cache_gateway:
  #@schema/doc "Base64-encoded cert for the log cache gateway."
  #@schema/type "string"
  crt: ~
  #@schema/doc "Base64-encoded private key for the log cache gateway cert."
  #@schema/type "string"
  key: ~

#@schema/doc "log-cache syslog configuration."
log_cache_syslog:
  #@schema/doc "Base64-encoded cert for the log cache syslog server requires CN of log-cache-syslog."
  #@schema/type "string"
  crt: ~
  #@schema/doc "Base64-encoded private key for the log cache syslog cert."
  #@schema/type "string"
  key: ~

#@schema/doc "log-cache client configuration."
client:
  #@schema/type "string"
  id: ~
  #@schema/type "string"
  secret: ~
