#@schema attach="data/values"
---
#@schema/doc "The kubernetes namespace where the system components will be deployed."
system_namespace: ""
#@schema/doc "The kubernetes namespace where the end-user workloads will be deployed."
workloads_namespace: ""

#@schema/doc "The base DNS domain for this instance of CF."
#@schema/example "system.cf.example.com"
system_domain: ""
#@schema/doc "One or more DNS domain names that this instance of CF will host end-user workloads upon."
#@schema/example ["apps.cf.example.com"]
app_domains: []

#@schema/title "CF Admin Password"
#@schema/doc "The password for the admin user in plain text."
cf_admin_password: ""

#@schema/title "CF Blobstore"
#@schema/doc "The control deployment of a blobstore for CF."
cf_blobstore:
  #@schema/doc "The minio access key ID."
  access_key: ""
  #@schema/doc "The minio secret access key."
  secret_key: ""

#@schema/title "CF DB"
#@schema/doc "(Optional) The control deployment of a database for CF."
#@schema/allow-empty
cf_db:
  #@schema/doc "The admin password for operators to access the CF database."
  admin_password: ""
  #@schema/doc "The boolean to enable the CF database."
  enabled: true


#@schema/title "Istio Static IP"
#@schema/doc "The reserved static IP for the istio ingress LoadBalancer."
istio_static_ip: ""

#@schema/doc "The image locations of various components."
images:
  #@schema/title "CAPI"
  #@schema/doc "The image location of CAPI."
  capi: ""
  #@schema/doc "The image location of Nginx."
  nginx: ""
  #@schema/title "cfroutesync"
  #@schema/doc "The image location of cfroutesync."
  cfroutesync: "gcr.io/cf-networking-images/cf-k8s-networking/cfroutesync@sha256:3b2b25614d6da572175a848003e379894b154dd719f2e77a2325b98ad857d416"

#@schema/doc "The reserved static IP for the istio ingress LoadBalancer."
system_certificate:
  #@schema/doc "The base64-encoded certificate for the wildcard subdomain of the system domain (e.g., CN=*.system.cf.example.com)."
  crt: ""
  #@schema/doc "The base64-encoded private key for the certificate above."
  key: ""
  #@schema/doc "The base64-encoded CA certificate used to sign the system certifcate."
  ca: ""

#! TODO: stopped adding "excessive" titles and docs here
capi:
  blobstore:
    #@schema/doc "The directory to be used for storing packages."
    package_directory_key: cc-packages
    #@schema/doc "The directory to be used for storing droplets."
    droplet_directory_key: cc-droplets
    #@schema/doc "The directory to be used for storing resources."
    resource_directory_key: cc-resources
    #@schema/doc "The directory to be used for storing buildpacks."
    buildpack_directory_key: cc-buildpacks
    #@schema/doc "The region of the blobstore."
    #! TODO: what is this about?
    region: "'"
    #@schema/doc "The kubernetes URL of the blobstore."
    endpoint: "http://cf-blobstore-minio.cf-blobstore.svc.cluster.local:9000"
  database:
    #@schema/examples ("Postgres", "postgres"), ("MySQL", "mysql")
    adapter: postgres
    host: ""
    #@schema/examples ("Postgres", 5432), ("MySQL", 3306)
    port: 5432
    user: cloud_controller
    #@schema/doc "The DB user password in plain text."
    password: ""
    name: cloud_controller

uaa:
  #@schema/doc "The client secret for the UAA admin client in plain text."
  admin_client_secret: ""

  database:
    #@schema/examples ("Postgres", "postgres"), ("MySQL", "mysql")
    #! TODO: is "postgresql" right? "postgres" is used above in ccdb example
    adapter: postgresql
    host: ""
    #@schema/examples ("Postgres", 5432), ("MySQL", 3306)
    port: 5432
    user: uaa
    #@schema/doc "The DB user password in plain text."
    password: ""
    name: uaa

  certificate:
    #@schema/doc "The base64-encoded certificate for the uaa service inside the kubernetes cluster (i.e., CN=uaa.cf-system.svc.cluster.local)."
    crt: ""
    #@schema/doc "The base64-encoded private key for the cert above."
    key: ""

  #@schema/doc "Java Web Token (JWT) configuration."
  jwt_policy:
    key_id: ""
    #@schema/doc "The private key in plain text."
    signing_key: ""

  encryption_key:
    #@schema/doc "The key label for the encryption passphrase."
    #@schema/example "key-1"
    label: ""
    #@schema/doc "The passphrase in plain text."
    passphrase: ""

  login:
    service_provider:
      #@schema/doc "The private key in plain text."
      key: ""
      #@schema/doc "The password in plain text."
      key_password: ""
      #@schema/doc "The certificate in plain text."
      certificate: ""

  login_secret_name: ""

doppler:
  tls:
    #@schema/doc "Base64-encoded certificate for the doppler service inside the kubernetes cluster (i.e., CN=doppler.cf-system.svc.cluster.local)."
    crt: ""
    #@schema/doc "Base64-encoded private key for the cert above."
    key: ""

eirini:
  tls:
    #@schema/doc "Base64-encoded certificate for the eirini service inside the kubernetes cluster (i.e., CN=eirini.cf-system.svc.cluster.local)."
    crt: ""
    #@schema/doc "Base64-encoded private key for the cert above."
    key: ""

log_cache_ca:
  #@schema/doc "Base64-encoded ca for the log cache."
  crt: ""
  #@schema/doc "Base64-encoded private key for the cert above."
  key: ""

log_cache:
  #@schema/doc "Base64-encoded cert for the log cache requires CN of log-cache."
  crt: ""
  #@schema/doc "Base64-encoded private key for the cert above."
  key: ""

log_cache_metrics:
  #@schema/doc "Base64-encoded cert for the log cache metrics requires CN of log-cache-metrics."
  crt: ""
  #@schema/doc "Base64-encoded private key for the cert above."
  key: ""

log_cache_gateway:
  #@schema/doc "Base64-encoded cert for the log cache gateway requires CN of log-cache-gateway."
  crt: ""
  #@schema/doc "Base64-encoded private key for the cert above."
  key: ""

log_cache_syslog:
  #@schema/doc "Base64-encoded cert for the log cache syslog server requires CN of log-cache-syslog."
  crt: ""
  #@schema/doc "Base64-encoded private key for the cert above."
  key: ""

log_cache_client:
  id: ""
  secret: ""

app_registry:
  hostname: ""
  repository: ""
  username: ""
  password: ""

metric_proxy:
  ca:
    #@schema/doc "The secret containing information of the metric proxy CA."
    #@schema/example "metric-proxy-ca"
    secret_name: ""
    crt: ""
    key: ""
  cert:
    #@schema/doc "The secret containing information of the metric proxy certificate."
    #@schema/example "metric-proxy-cert"
    secret_name: ""
    crt: ""
    key: ""
